node {
    // This step should not normally be used in your script. Consult the inline help for details.
    withDockerContainer(args: '-v /root/.m2:/root/.m2', image: 'maven:3.9.0') {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
    }
    stage('Test') {
        sh 'mvn test'
        post.always {
            junit 'target/surefire-reports/*.xml'
        }
    }
}
